- name: Run 'show version' on all routers
  hosts: dcrouters
  connection: network_cli
  gather_facts: false
  vars_prompt:
    - name: ansible_user
      prompt: "Enter your SSH username"
      private: false

    - name: ansible_ssh_pass
      prompt: "Enter your SSH password"
      private: yes

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Execute show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_ver_output

    - name: Display output
      debug:
        var: show_ver_output.stdout_lines
