- name: Run 'show version' on all routers
  hosts: dcrouters
  gather_facts: no
  vars_prompt:
    - name: ansible_user
      prompt: "Enter your SSH username"
      private: no

    - name: ansible_ssh_pass
      prompt: "Enter your SSH password"
      private: yes

  tasks:
    - name: Execute show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_ver_output

    - name: Display output
      debug:
        var: show_ver_output.stdout_lines
