- name: create/update prefix-list enteries
  hosts: dcrouters
  connection: network_cli
  gather_facts: false
  
  vars_prompt:
    - name: ansible_user
      prompt: "Enter your SSH username"
      private: false

    - name: ansible_ssh_pass
      prompt: "Enter your SSH password"
      private: true

    - name: ansible_become_pass
      prompt: "Enter your enable (privilege) password"
      private: true

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Update prefix-list enteries
      cisco.ios.ios_prefix_lists:
        config:
          - afi: ipv4
            prefix_lists:
              - name: NXC_ROUTES_TO_STOPHELP
                description: Update utbound Routes to StopHelp
                entries:
                  - action: permit
                    prefix: 10.20.20.0/24
                    sequence: 30
        state: merged
