---
- name: Push both STOPHELP prefix‐lists to IOS routers
  hosts: dcrouters
  connection: network_cli
  gather_facts: false

  vars_prompt:
    - name: ansible_user
      prompt: "Enter Username"
      private: false

    - name: ansible_ssh_pass
      prompt: "Enter Password"
      private: true

    - name: ansible_become_pass
      prompt: "Enter Enable Pword"
      private: true

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  vars_files:
    - stophelp_routes_in.yml

  tasks:
    - name: Preview “in” and “to” subnet lists
      debug:
        msg:
          - "STOPHELP_ROUTES_IN → {{ stophelp_routes_in | map(attribute='prefix') | list }}"
          - "STOPHELP_ROUTES_TO → {{ stophelp_routes_to | map(attribute='prefix') | list }}"

    - name: Pause for confirmation
      ansible.builtin.pause:
        prompt: "Press Enter to continue (Ctrl+C to abort)"

    - name: Create/update both STOPHELP prefix‐lists on IOS
      cisco.ios.ios_prefix_lists:
        config:
          - afi: ipv4
            prefix_lists:
              - name: STOPHELP_ROUTES_IN
                description: "Imported from fromStophelp"
                entries: "{{ stophelp_routes_in }}"
        
              - name: STOPHELP_ROUTES_TO
                description: "Imported from toStophelp"
                entries: "{{ stophelp_routes_to }}"
        state: replaced
