---
- name: Push STOPHELP_ROUTES_IN prefix-list to IOS routers
  hosts: dcrouters
  connection: network_cli
  gather_facts: false

  vars_prompt:
    - name: ansible_user
      prompt: "Enter your SSH username"
      private: false

    - name: ansible_ssh_pass
      prompt: "Enter your SSH password"
      private: true

    - name: ansible_become_pass
      prompt: "Enter your enable (privilege) password"
      private: true

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  # ─── Load the generated YAML that contains our “stophelp_routes_in:” list ───
  vars_files:
    - stophelp_routes_in.yml

  tasks:
    - name: Print the subnets that will be added to STOPHELP_ROUTES_IN
      debug:
        msg:
          - "You are about to push the following subnets into the STOPHELP_ROUTES_IN prefix-list:"
          - ""
          - "{{ stophelp_routes_in | map(attribute='prefix') | list }}"

    - name: Please acknowledge to continue
      ansible.builtin.pause:
        prompt: "Press Enter to continue (Ctrl+C to abort)"
        
    - name: Create/update STOPHELP_ROUTES_IN on IOS
      cisco.ios.ios_prefix_lists:
        config:
          - afi: ipv4
            prefix_lists:
              - name: STOPHELP_ROUTES_IN
                description: "Imported from stophelpPrefixlist.yaml"
                entries: "{{ stophelp_routes_in }}"
