---
- name: Push both STOPHELP prefix‐lists to IOS routers
  hosts: dcrouters
  connection: network_cli
  gather_facts: false

  vars_prompt:
    - name: ansible_user
      prompt: "Enter Username"
      private: false

    - name: ansible_ssh_pass
      prompt: "Enter Password"
      private: true

    - name: ansible_become_pass
      prompt: "Enter Enable Pword"
      private: true

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  vars_files:
    - stophelp_routes_in.yml

  tasks:
    - name: Get current 'in' prefix list
      set_fact:
        existing_prefix_in: "{{ existing_prefix_in_output | map(attribute='prefix') | list }}"

    - name: Get current 'to' prefix list
      set_fact:
        existing_prefix_to: "{{ existing_prefix_to_output | map(attribute='prefix') | list }}"

    - name: Determine prefixes to add and remove (IN list)
      set_fact:
        add_prefix_in: "{{ stophelp_routes_in | map(attribute='prefix') | difference(existing_prefix_in) | list }}"
        remove_prefix_in: "{{ existing_prefix_in | difference(stophelp_routes_in | map(attribute='prefix') | list) }}"

    - name: Determine prefixes to add and remove (TO list)
      set_fact:
        add_prefix_to: "{{ stophelp_routes_to | map(attribute='prefix') | difference(existing_prefix_to) | list }}"
        remove_prefix_to: "{{ existing_prefix_to | difference(stophelp_routes_to | map(attribute='prefix') | list) }}"

    - name: Preview prefix-list changes
      debug:
        msg:
          - "IN - Prefixes to ADD → {{ add_prefix_in }}"
          - "IN - Prefixes to REMOVE → {{ remove_prefix_in }}"
          - "TO - Prefixes to ADD → {{ add_prefix_to }}"
          - "TO - Prefixes to REMOVE → {{ remove_prefix_to }}"

    - name: Pause for confirmation
      ansible.builtin.pause:
        prompt: "Press Enter to continue (Ctrl+C to abort)"

    - name: Update Stophelp Prefix-list on DC WAN - From Stophelp
      cisco.ios.ios_prefix_lists:
        config:
        - afi: ipv4
          prefix_lists:
            - name: "STOPHELP_ROUTES_IN"
              description: "Imported from fromStophelp"
              entries: "{{ stophelp_routes_in }}"
        state: replaced
      tags: FROM

    - name: Update Stophelp Prefix-list on DC WAN - To Stophelp
      cisco.ios.ios_prefix_lists:
        config:
        - afi: ipv4
          prefix_lists:
            - name: STOPHELP_ROUTES_TO
              description: "Imported from toStophelp"
              entries: "{{ stophelp_routes_to }}"
        state: replaced
      tags: TO

    - name: Clear BGP Neighbors Soft
      cisco.ios.ios_command:
        commands:
          - clear ip bgp * soft out
          - clear ip bgp * soft in
      tags: TO, FROM
