[dcrouters]
vIOS4-wan ansible_host=172.17.1.6 ansible_user=chris
vIOS3-wan ansible_host=172.17.1.5 ansible_user=chris

[dcrouters:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_command_timeout=60
ansible_become=false

ansible_user=chris
ansible_password=P33k@b002026

ansible_network_cli_ssh_type=libssh
ansible_libssh_host_key_auto_add=true
ansible_libssh_hostkeys=+ssh-rsa
ansible_libssh_key_exchange_algorithms=+diffie-hellman-group14-sha1


[switches]
#cdccr1 ansible_host=192.168.1.6 ansible_user=chris
